# Makefile for tasks

task1: task1.cpp
	g++ -o task1 task1.cpp -g -std=c++11 -lpthread

task2: task2.cpp
	g++ -o task2 task2.cpp -g -std=c++11 -lpthread

task3: task3.cpp
	g++ -o task3 task3.cpp -g -std=c++11 -lpthread

task4: task4.cpp
	g++ -o task4 task4.cpp -O0 -g -std=c++11 -lpthread

task5: task5.cpp
	g++ -o task5 task5.cpp -g -std=c++11 -lpthread

d: task1.cpp task2.cpp task3.cpp task4.cpp task5.cpp
	rm task1 task2 task3 task4 task5
